// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `Forum.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __Forum_h__
#define __Forum_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/GCObject.h>
#include <Ice/AsyncResult.h>
#include <Ice/Incoming.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 306
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace Forum
{

class ForumInterface;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::Forum::ForumInterface>&);
::IceProxy::Ice::Object* upCast(::IceProxy::Forum::ForumInterface*);

}

}

namespace Forum
{

class ForumInterface;
bool operator==(const ForumInterface&, const ForumInterface&);
bool operator<(const ForumInterface&, const ForumInterface&);
::Ice::Object* upCast(::Forum::ForumInterface*);
typedef ::IceInternal::Handle< ::Forum::ForumInterface> ForumInterfacePtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::Forum::ForumInterface> ForumInterfacePrx;
void __patch(ForumInterfacePtr&, const ::Ice::ObjectPtr&);

}

namespace Forum
{

struct UserInfo
{
    ::Ice::Int id;
    ::std::string name;

    bool operator==(const UserInfo& __rhs) const
    {
        if(this == &__rhs)
        {
            return true;
        }
        if(id != __rhs.id)
        {
            return false;
        }
        if(name != __rhs.name)
        {
            return false;
        }
        return true;
    }

    bool operator<(const UserInfo& __rhs) const
    {
        if(this == &__rhs)
        {
            return false;
        }
        if(id < __rhs.id)
        {
            return true;
        }
        else if(__rhs.id < id)
        {
            return false;
        }
        if(name < __rhs.name)
        {
            return true;
        }
        else if(__rhs.name < name)
        {
            return false;
        }
        return false;
    }

    bool operator!=(const UserInfo& __rhs) const
    {
        return !operator==(__rhs);
    }
    bool operator<=(const UserInfo& __rhs) const
    {
        return operator<(__rhs) || operator==(__rhs);
    }
    bool operator>(const UserInfo& __rhs) const
    {
        return !operator<(__rhs) && !operator==(__rhs);
    }
    bool operator>=(const UserInfo& __rhs) const
    {
        return !operator<(__rhs);
    }
};

}

namespace Ice
{
template<>
struct StreamableTraits< ::Forum::UserInfo>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 5;
    static const bool fixedLength = false;
};

template<class S>
struct StreamWriter< ::Forum::UserInfo, S>
{
    static void write(S* __os, const ::Forum::UserInfo& v)
    {
        __os->write(v.id);
        __os->write(v.name);
    }
};

template<class S>
struct StreamReader< ::Forum::UserInfo, S>
{
    static void read(S* __is, ::Forum::UserInfo& v)
    {
        __is->read(v.id);
        __is->read(v.name);
    }
};

}

namespace Forum
{

class Callback_ForumInterface_sayHello_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_ForumInterface_sayHello_Base> Callback_ForumInterface_sayHelloPtr;

class Callback_ForumInterface_getUserInfo_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_ForumInterface_getUserInfo_Base> Callback_ForumInterface_getUserInfoPtr;

}

namespace IceProxy
{

namespace Forum
{

class ForumInterface : virtual public ::IceProxy::Ice::Object
{
public:

    void sayHello(const ::std::string& __p_str)
    {
        sayHello(__p_str, 0);
    }
    void sayHello(const ::std::string& __p_str, const ::Ice::Context& __ctx)
    {
        sayHello(__p_str, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_sayHello(const ::std::string& __p_str, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_sayHello(__p_str, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_sayHello(const ::std::string& __p_str, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_sayHello(__p_str, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_sayHello(const ::std::string& __p_str, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_sayHello(__p_str, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_sayHello(const ::std::string& __p_str, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_sayHello(__p_str, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_sayHello(const ::std::string& __p_str)
    {
        return begin_sayHello(__p_str, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_sayHello(const ::std::string& __p_str, const ::Ice::Context& __ctx)
    {
        return begin_sayHello(__p_str, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_sayHello(const ::std::string& __p_str, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_sayHello(__p_str, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_sayHello(const ::std::string& __p_str, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_sayHello(__p_str, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_sayHello(const ::std::string& __p_str, const ::Forum::Callback_ForumInterface_sayHelloPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_sayHello(__p_str, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_sayHello(const ::std::string& __p_str, const ::Ice::Context& __ctx, const ::Forum::Callback_ForumInterface_sayHelloPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_sayHello(__p_str, &__ctx, __del, __cookie);
    }

    void end_sayHello(const ::Ice::AsyncResultPtr&);
    
private:

    void sayHello(const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_sayHello(const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void getUserInfo(::Ice::Int __p_id, ::Forum::UserInfo& __p_user_info)
    {
        getUserInfo(__p_id, __p_user_info, 0);
    }
    void getUserInfo(::Ice::Int __p_id, ::Forum::UserInfo& __p_user_info, const ::Ice::Context& __ctx)
    {
        getUserInfo(__p_id, __p_user_info, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_getUserInfo(::Ice::Int __p_id, const ::IceInternal::Function<void (const ::Forum::UserInfo&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_getUserInfo(__p_id, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_getUserInfo(::Ice::Int __p_id, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_getUserInfo(__p_id, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_getUserInfo(::Ice::Int __p_id, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Forum::UserInfo&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_getUserInfo(__p_id, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_getUserInfo(::Ice::Int __p_id, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_getUserInfo(__p_id, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_getUserInfo(::Ice::Int __p_id, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::Forum::UserInfo&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent);
    
public:
#endif

    ::Ice::AsyncResultPtr begin_getUserInfo(::Ice::Int __p_id)
    {
        return begin_getUserInfo(__p_id, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getUserInfo(::Ice::Int __p_id, const ::Ice::Context& __ctx)
    {
        return begin_getUserInfo(__p_id, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getUserInfo(::Ice::Int __p_id, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getUserInfo(__p_id, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getUserInfo(::Ice::Int __p_id, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getUserInfo(__p_id, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getUserInfo(::Ice::Int __p_id, const ::Forum::Callback_ForumInterface_getUserInfoPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getUserInfo(__p_id, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getUserInfo(::Ice::Int __p_id, const ::Ice::Context& __ctx, const ::Forum::Callback_ForumInterface_getUserInfoPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getUserInfo(__p_id, &__ctx, __del, __cookie);
    }

    void end_getUserInfo(::Forum::UserInfo& __p_user_info, const ::Ice::AsyncResultPtr&);
    
private:

    void getUserInfo(::Ice::Int, ::Forum::UserInfo&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_getUserInfo(::Ice::Int, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<ForumInterface> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<ForumInterface*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<ForumInterface> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<ForumInterface*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<ForumInterface> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<ForumInterface*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<ForumInterface> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<ForumInterface*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<ForumInterface> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<ForumInterface*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<ForumInterface> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<ForumInterface*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<ForumInterface> ice_secure(bool __secure) const
    {
        return dynamic_cast<ForumInterface*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<ForumInterface> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<ForumInterface*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<ForumInterface> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<ForumInterface*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<ForumInterface> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<ForumInterface*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<ForumInterface> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<ForumInterface*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<ForumInterface> ice_invocationTimeout(int __timeout) const
    {
        return dynamic_cast<ForumInterface*>(::IceProxy::Ice::Object::ice_invocationTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<ForumInterface> ice_twoway() const
    {
        return dynamic_cast<ForumInterface*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<ForumInterface> ice_oneway() const
    {
        return dynamic_cast<ForumInterface*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<ForumInterface> ice_batchOneway() const
    {
        return dynamic_cast<ForumInterface*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<ForumInterface> ice_datagram() const
    {
        return dynamic_cast<ForumInterface*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<ForumInterface> ice_batchDatagram() const
    {
        return dynamic_cast<ForumInterface*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<ForumInterface> ice_compress(bool __compress) const
    {
        return dynamic_cast<ForumInterface*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<ForumInterface> ice_timeout(int __timeout) const
    {
        return dynamic_cast<ForumInterface*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<ForumInterface> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<ForumInterface*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<ForumInterface> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<ForumInterface*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace Forum
{

class ForumInterface : virtual public ::Ice::Object
{
public:

    typedef ForumInterfacePrx ProxyType;
    typedef ForumInterfacePtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void sayHello(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___sayHello(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void getUserInfo(::Ice::Int, ::Forum::UserInfo&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___getUserInfo(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
};

inline bool operator==(const ForumInterface& l, const ForumInterface& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const ForumInterface& l, const ForumInterface& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace Forum
{

template<class T>
class CallbackNC_ForumInterface_sayHello : public Callback_ForumInterface_sayHello_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_ForumInterface_sayHello(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_ForumInterface_sayHelloPtr
newCallback_ForumInterface_sayHello(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ForumInterface_sayHello<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_ForumInterface_sayHelloPtr
newCallback_ForumInterface_sayHello(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ForumInterface_sayHello<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_ForumInterface_sayHelloPtr
newCallback_ForumInterface_sayHello(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ForumInterface_sayHello<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_ForumInterface_sayHelloPtr
newCallback_ForumInterface_sayHello(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ForumInterface_sayHello<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_ForumInterface_sayHello : public Callback_ForumInterface_sayHello_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_ForumInterface_sayHello(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_ForumInterface_sayHelloPtr
newCallback_ForumInterface_sayHello(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ForumInterface_sayHello<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_ForumInterface_sayHelloPtr
newCallback_ForumInterface_sayHello(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ForumInterface_sayHello<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_ForumInterface_sayHelloPtr
newCallback_ForumInterface_sayHello(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ForumInterface_sayHello<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_ForumInterface_sayHelloPtr
newCallback_ForumInterface_sayHello(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ForumInterface_sayHello<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_ForumInterface_getUserInfo : public Callback_ForumInterface_getUserInfo_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::Forum::UserInfo&);

    CallbackNC_ForumInterface_getUserInfo(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Forum::ForumInterfacePrx __proxy = ::Forum::ForumInterfacePrx::uncheckedCast(__result->getProxy());
        ::Forum::UserInfo user_info;
        try
        {
            __proxy->end_getUserInfo(user_info, __result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::CallbackNC<T>::_callback.get()->*_response)(user_info);
        }
    }

    private:

    Response _response;
};

template<class T> Callback_ForumInterface_getUserInfoPtr
newCallback_ForumInterface_getUserInfo(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::Forum::UserInfo&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ForumInterface_getUserInfo<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_ForumInterface_getUserInfoPtr
newCallback_ForumInterface_getUserInfo(T* instance, void (T::*cb)(const ::Forum::UserInfo&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_ForumInterface_getUserInfo<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_ForumInterface_getUserInfo : public Callback_ForumInterface_getUserInfo_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::Forum::UserInfo&, const CT&);

    Callback_ForumInterface_getUserInfo(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), _response(cb)
    {
    }

    virtual void completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Forum::ForumInterfacePrx __proxy = ::Forum::ForumInterfacePrx::uncheckedCast(__result->getProxy());
        ::Forum::UserInfo user_info;
        try
        {
            __proxy->end_getUserInfo(user_info, __result);
        }
        catch(const ::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::exception(__result, ex);
            return;
        }
        if(_response)
        {
            (::IceInternal::Callback<T, CT>::_callback.get()->*_response)(user_info, CT::dynamicCast(__result->getCookie()));
        }
    }

    private:

    Response _response;
};

template<class T, typename CT> Callback_ForumInterface_getUserInfoPtr
newCallback_ForumInterface_getUserInfo(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::Forum::UserInfo&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ForumInterface_getUserInfo<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_ForumInterface_getUserInfoPtr
newCallback_ForumInterface_getUserInfo(T* instance, void (T::*cb)(const ::Forum::UserInfo&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_ForumInterface_getUserInfo<T, CT>(instance, cb, excb, sentcb);
}

}

#include <IceUtil/PopDisableWarnings.h>
#endif
