// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `Forum.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <Forum.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/BasicStream.h>
#include <IceUtil/Iterator.h>
#include <IceUtil/PopDisableWarnings.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 306
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __Forum__ForumInterface__sayHello_name = "sayHello";

const ::std::string __Forum__ForumInterface__getUserInfo_name = "getUserInfo";

}

namespace Ice
{
}
::IceProxy::Ice::Object* ::IceProxy::Forum::upCast(::IceProxy::Forum::ForumInterface* p) { return p; }

void
::IceProxy::Forum::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::Forum::ForumInterface>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::Forum::ForumInterface;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::Forum::ForumInterface::sayHello(const ::std::string& __p_str, const ::Ice::Context* __ctx)
{
    ::IceInternal::Outgoing __og(this, __Forum__ForumInterface__sayHello_name, ::Ice::Normal, __ctx);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_str);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    __invoke(__og);
}

::Ice::AsyncResultPtr
IceProxy::Forum::ForumInterface::begin_sayHello(const ::std::string& __p_str, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __Forum__ForumInterface__sayHello_name, __del, __cookie);
    try
    {
        __result->prepare(__Forum__ForumInterface__sayHello_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_str);
        __result->endWriteParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

void
IceProxy::Forum::ForumInterface::end_sayHello(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __Forum__ForumInterface__sayHello_name);
}

void
IceProxy::Forum::ForumInterface::getUserInfo(::Ice::Int __p_id, ::Forum::UserInfo& __p_user_info, const ::Ice::Context* __ctx)
{
    __checkTwowayOnly(__Forum__ForumInterface__getUserInfo_name);
    ::IceInternal::Outgoing __og(this, __Forum__ForumInterface__getUserInfo_name, ::Ice::Normal, __ctx);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_id);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    if(!__og.invoke())
    {
        try
        {
            __og.throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
            throw __uue;
        }
    }
    ::IceInternal::BasicStream* __is = __og.startReadParams();
    __is->read(__p_user_info);
    __og.endReadParams();
}

::Ice::AsyncResultPtr
IceProxy::Forum::ForumInterface::begin_getUserInfo(::Ice::Int __p_id, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__Forum__ForumInterface__getUserInfo_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __Forum__ForumInterface__getUserInfo_name, __del, __cookie);
    try
    {
        __result->prepare(__Forum__ForumInterface__getUserInfo_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_id);
        __result->endWriteParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

#ifdef ICE_CPP11

::Ice::AsyncResultPtr
IceProxy::Forum::ForumInterface::__begin_getUserInfo(::Ice::Int __p_id, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::Forum::UserInfo&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
{
    class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
    {
    public:

        Cpp11CB(const ::std::function<void (const ::Forum::UserInfo&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
            ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
            _response(responseFunc)
        {
            CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
        }

        virtual void completed(const ::Ice::AsyncResultPtr& __result) const
        {
            ::Forum::ForumInterfacePrx __proxy = ::Forum::ForumInterfacePrx::uncheckedCast(__result->getProxy());
            ::Forum::UserInfo __p_user_info;
            try
            {
                __proxy->end_getUserInfo(__p_user_info, __result);
            }
            catch(const ::Ice::Exception& ex)
            {
                Cpp11FnCallbackNC::exception(__result, ex);
                return;
            }
            if(_response != nullptr)
            {
                _response(__p_user_info);
            }
        }
    
    private:
        
        ::std::function<void (const ::Forum::UserInfo&)> _response;
    };
    return begin_getUserInfo(__p_id, __ctx, new Cpp11CB(__response, __exception, __sent));
}
#endif

void
IceProxy::Forum::ForumInterface::end_getUserInfo(::Forum::UserInfo& __p_user_info, const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __Forum__ForumInterface__getUserInfo_name);
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    ::IceInternal::BasicStream* __is = __result->__startReadParams();
    __is->read(__p_user_info);
    __result->__endReadParams();
}

const ::std::string&
IceProxy::Forum::ForumInterface::ice_staticId()
{
    return ::Forum::ForumInterface::ice_staticId();
}

::IceProxy::Ice::Object*
IceProxy::Forum::ForumInterface::__newInstance() const
{
    return new ForumInterface;
}

::Ice::Object* Forum::upCast(::Forum::ForumInterface* p) { return p; }

namespace
{
const ::std::string __Forum__ForumInterface_ids[2] =
{
    "::Forum::ForumInterface",
    "::Ice::Object"
};

}

bool
Forum::ForumInterface::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__Forum__ForumInterface_ids, __Forum__ForumInterface_ids + 2, _s);
}

::std::vector< ::std::string>
Forum::ForumInterface::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__Forum__ForumInterface_ids[0], &__Forum__ForumInterface_ids[2]);
}

const ::std::string&
Forum::ForumInterface::ice_id(const ::Ice::Current&) const
{
    return __Forum__ForumInterface_ids[0];
}

const ::std::string&
Forum::ForumInterface::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::Forum::ForumInterface";
    return typeId;
#else
    return __Forum__ForumInterface_ids[0];
#endif
}

::Ice::DispatchStatus
Forum::ForumInterface::___sayHello(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::std::string __p_str;
    __is->read(__p_str);
    __inS.endReadParams();
    sayHello(__p_str, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
Forum::ForumInterface::___getUserInfo(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::Ice::Int __p_id;
    __is->read(__p_id);
    __inS.endReadParams();
    ::Forum::UserInfo __p_user_info;
    getUserInfo(__p_id, __p_user_info, __current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__p_user_info);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __Forum__ForumInterface_all[] =
{
    "getUserInfo",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "sayHello"
};

}

::Ice::DispatchStatus
Forum::ForumInterface::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__Forum__ForumInterface_all, __Forum__ForumInterface_all + 6, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __Forum__ForumInterface_all)
    {
        case 0:
        {
            return ___getUserInfo(in, current);
        }
        case 1:
        {
            return ___ice_id(in, current);
        }
        case 2:
        {
            return ___ice_ids(in, current);
        }
        case 3:
        {
            return ___ice_isA(in, current);
        }
        case 4:
        {
            return ___ice_ping(in, current);
        }
        case 5:
        {
            return ___sayHello(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
Forum::ForumInterface::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
Forum::ForumInterface::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
Forum::__patch(ForumInterfacePtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::Forum::ForumInterfacePtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::Forum::ForumInterface::ice_staticId(), v);
    }
}
