
all:
	#g++ -std=c++11 -o test  main.cpp -I/usr/local/include -L/usr/local/lib -ljsoncpp
	g++ -std=c++11 -o test  main.cpp -I/opt/jsoncpp-0.5.0/include -L/opt/jsoncpp-0.5.0/lib -ljsoncpp
clean:
	rm test
